### ISSUE TITLE
你好，firefox下滚动无反应，我本地已做修改

### ISSUE THREAD

**Issue by sx1989827** [river-lee/vue-fullpage#1]
你好，看了你的代码，你的鼠标滚轮监听的是mousewheel，在firefox有问题，我把监听的mousewheel修改为
(("onwheel" in document.createElement("div")) ? "wheel" :(document.onmousewheel !== undefined ? "mousewheel" : "DOMMouseScroll"))  然后就可以兼容firefox了，望你这边修改下代码，重新发个包

**Comment by abel-oye** [comment]
之前是有针对性的处理，忽略了firefox。感谢你的提出。
我已修复了这个问题。除了mousewheel不支持，event.wheelDelta 也一样。都做了兼容处理。并移除了滚轮的距离判断改为方向判断。后面如果还有其他问题请及时指出
