### ISSUE TITLE
Mobile scroll issue

### ISSUE THREAD

**Issue by huy-tran** [river-lee/vue-fullpage#10]
Hi I am using your plugin on my charity project which I really like.

http://www.shekinahgloryacademy.co.ke/

It works perfectly on desktop but mobile. I can't scroll unless touching the little green navigation dots on right hand side.

It's great if you can help me fix this one out.

Many thanks

**Comment by abel-oye** [comment]
Thank you for your use。

The reason why you can't slide is to set up "der: 1",Please set it to 0.1 or not set.

**Comment by huy-tran** [comment]
Hi @river-lee thanks for your prompt reply.

I tried to set **der: 1** or even remove it but still can't scroll on mobile.

Also what does **der** stand for ?

Cheers !

**Comment by abel-oye** [comment]
Set “der” to 0.1, I've tested it

**Comment by huy-tran** [comment]
Hi @river-lee ,

I recently set "der" to 0.1 and nothing has changed. It's great if you can give the website a quick test.

Below are my settings

```
data() {
            return {
                currentSection: 0,
                donationClick: false,

                fullpageOptions: {
                    duration: 5000,
                    der: 0.1,
                    afterChange: (el, current) => {
                        this.currentSection = current;
                    }
                }
            };
        },
```

Thanks mate !

**Comment by abel-oye** [comment]
see https://jsfiddle.net/6jc3okaq/21/。
“der” is used to control the distance of the sliding to trigger the movement. “der” is 1(100%) that needs to slide from the head to the end.
