### ISSUE TITLE
在IE11下不能用鼠标滚轮滚动屏幕

### ISSUE THREAD

**Issue by jiaozhouzhou** [river-lee/vue-fullpage#13]
鼠标拖拽可以滚动，滚轮不能滚动，官方的例子也是这样，有什么可以解决的方案吗？

**Comment by abel-oye** [comment]
Fixed

**Comment by jiaozhouzhou** [comment]
具体是要怎么做？

**Comment by abel-oye** [comment]
Update version 1.7.4

**Comment by jiaozhouzhou** [comment]
更新到1.7.4后滚动滚轮直接就到最有一页，然后继续向下滚动滚轮是滚到上一页，向上滚轮是滚动到下一页。

**Comment by jiaozhouzhou** [comment]
由于滚轮的事件现在刚好相反，我开启了 loop: true 所以就到最后一页。可以把滚轮的上下滚动事件修复下吗？
