### ISSUE TITLE
How do I add an exit animation to each page

### ISSUE THREAD

**Issue by jiaozhouzhou** [river-lee/vue-fullpage#14]

**Comment by abel-oye** [comment]
The official example did not consider exit, but it could be controlled by `options.afterChange`.

**Comment by jiaozhouzhou** [comment]
use options.afterChange Generate a new animation object for v-animate,Is that right?

**Comment by abel-oye** [comment]
v-animate support it ,srroy ,It needs to be realized by yourself. 
For example:
beforeChange:function(){
//remove exit animation
}
afterChange:function(elem){
   //add exit animation
}
