### ISSUE TITLE
how move to page after page reloading

### ISSUE THREAD

**Issue by psaruks** [river-lee/vue-fullpage#15]
After reloading page, it`s default starts on first page, but how to scroll to the page on which the user reloaded the page. I had a solution with a cookie, but its doesnt work.. 
```
mounted() {
     this.$refs.fullpage.$fullpage.moveTo(2);
}
```

that doesnt work..

**Comment by abel-oye** [comment]
options.start = 2 [options](https://github.com/river-lee/vue-fullpage#options)

**Comment by psaruks** [comment]
scroll works inversively, and after options.start = 2 , scroll doesnt work at all

**Comment by abel-oye** [comment]
Update the version 1.7.3 [demo](https://river-lee.github.io/vue-fullpage/examples/)

**Comment by psaruks** [comment]
check your demo, scroll works inversively, i scroll down, but page moves up, and after page loaded, scroll with mouse doesnt work at all, only buttons scroll

**Comment by abel-oye** [comment]
Fiexd. Try again!

**Comment by psaruks** [comment]
why scroll work inversively? i scroll my mouse up, but they switch to next page, i scroll my mouse down and they switch to prev page

**Comment by psaruks** [comment]
? please inverse this

**Comment by psaruks** [comment]
https://jsfiddle.net/e23jiang/6jc3okaq/1/

compare with this..

**Comment by abel-oye** [comment]
https://jsfiddle.net/6jc3okaq/98/

**Comment by psaruks** [comment]
its inverse, they shouldn`t work like this!

there is correct scrolling https://jsfiddle.net/e23jiang/6jc3okaq/1/

**Comment by abel-oye** [comment]
What should it be?

**Comment by psaruks** [comment]
look at this
https://jsfiddle.net/e23jiang/6jc3okaq/1/
it should work like this!


in your fix it works inversively, and its not correct

**Comment by psaruks** [comment]
wait for fix?

**Comment by abel-oye** [comment]
Look at my [video](http://static.xiawan8.com/temp/WeChatSight273.mp4).  Is there any problem here?

**Comment by matthewchartier** [comment]
I am seeing an issue in your live demo. If you go to page 2 and resize the browser height, the pages don't resize and it leaves the layout showing multiple pages. Is there a known workaround to this issue?

**Comment by abel-oye** [comment]
I have added this feature to the new version. Please update 1.8.0.
