### ISSUE TITLE
More instructions

### ISSUE THREAD

**Issue by danyakov** [river-lee/vue-fullpage#18]
Hello,
can you provide more instructions about plugin?

For example, how to make menu work. I add @click="moveTo(2)", but no action and I receive error (method "moveTo" is not defined on the instance but referenced during render).

It is not clear how to fix this.

**Comment by abel-oye** [comment]
Do you define moveTo in methods?[https://github.com/river-lee/vue-fullpage/blob/master/examples/index.html#L137](https://github.com/river-lee/vue-fullpage/blob/master/examples/index.html#L137)
