### ISSUE TITLE
callback function problem

### ISSUE THREAD

**Issue by you06** [river-lee/vue-fullpage#23]
Hi, this tool is awesome, thank you for your working on vue-fullpage. I found some problems while using it.

I start with the options from README:
```javascript
export default {
  data() {
    return {
      opts: {
        start: 0,
        dir: 'v',
        duration: 500,
        beforeChange: function (prev, next) {
        },
        afterChange: function (prev, next) {
        }
      }
    }
  },
  method:{
    moveNext(){
      this.$refs.example.$fullpage.moveNext(); //Move to the next page
    }
  }
}
```

When I look into `beforeChange` function, `prev` is a DOM object, I think the parameters should be `beforeChange: function (html, prev, next)`

**Comment by abel-oye** [comment]
Thank you for your comments. "Before Change" and "After Change" mainly operate on slides rather than containers. If you need to operate on "el", you can use "this"

**Comment by you06** [comment]
@river-lee I'm not trying to operate on "el". I think there is a mistake in the demo options in README.

The second parameter is previous index and third is next index.

source code:
[https://github.com/river-lee/vue-fullpage/blob/master/src/libs/Fullpage.js#L276](https://github.com/river-lee/vue-fullpage/blob/master/src/libs/Fullpage.js#L276)

**Comment by abel-oye** [comment]
Sorry, the README is wrong. Should be [`beforeChange`](https://github.com/river-lee/vue-fullpage/blob/a56c156489aaee2a198051fc301b6c04baacac53/src/libs/Fullpage.js#L403)
