### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by DavidMGT** [river-lee/vue-fullpage#25]
node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@11.0.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@11.0.0 (node-v67 ABI) (falling back to source compile with node-gyp)

**Comment by abel-oye** [comment]
删掉依赖重新试一下。nodejs 11的版本我没有尝试过，也尝试切换版本试一下
