### ISSUE TITLE
How to refresh pages with vue 2

### ISSUE THREAD

**Issue by joelsantosbr** [river-lee/vue-fullpage#3]
I want use v-show with pages and reload fullpage with function, it is possible?

Refer https://github.com/alvarotrigo/fullPage.js#methods method reBuild()

Sorry for my english, i'm Brazillian, thanks a lot.

**Comment by abel-oye** [comment]
I'm sorry, I didn't understand your need, but I according to `reBuild` added a [$update](https://github.com/river-lee/vue-fullpage/blob/master/README.md#upadte) method, at the time of change in the DOM structure. [See Dome](https://river-lee.github.io/vue-fullpage/test/)
