### ISSUE TITLE
mouse left click AND moveTo has no animation

### ISSUE THREAD

**Issue by viniciusgugelmin** [river-lee/vue-fullpage#34]
Sup, I'm coding a slide site, and I need to "block" the switch of pages of the left click of mouse, I just want to switch the page with the scroll. The other issue is that the moveTo function is not working properly, I have a menu aSide that calls a event, that also calls the moveTo function. (I hope you can get it, I'm brazilian)

```
                     <li>
                        <a @click="moveTo(0, 'sobre')">
                            <span>
                                Sobre
                            </span>
                        </a>
                    </li>
```
```
mounted() {
            Event.$on('move-to', this.moveTo , this.slide)
            this.moveTo();
        },

methods: {
            moveTo(slide) {
                this.$refs.fpcontainer.$fullpage.moveTo(slide);
            }
        },
```

**Comment by abel-oye** [comment]
https://github.com/river-lee/vue-fullpage#moveto
add force param
