### ISSUE TITLE
How to scroll to the top of the page

### ISSUE THREAD

**Issue by impronta48** [river-lee/vue-fullpage#35]
Hi,
The last page of my fullpage slideshow is really long, so I use overflow scroll.

When the users goes back and then forward again I would like the long page to start from the top (and lot from the scrolling point where it was, is this possible, if so how?)

Example here: (see last page)
https://ebike.bikesquare.eu/baraggia/in-ebike-tra-risaie

Thanks
Massimo

**Comment by abel-oye** [comment]
See demo : [https://river-lee.github.io/vue-fullpage/examples/scroll.html](https://river-lee.github.io/vue-fullpage/examples/scroll.html).

https://github.com/river-lee/vue-fullpage#options options.overflow = 'scroll'
