### ISSUE TITLE
moveTo isn't working for the last slide

### ISSUE THREAD

**Issue by viniciusgugelmin** [river-lee/vue-fullpage#36]
I'm using the function moveTo to redirect to specifcs slides in my page. For example, if the url is /slide3, the page starts with slide number 3, but if the number 3 is the last it bugs and loads the first slide.

**Comment by abel-oye** [comment]
Can I have a look at the code?

**Comment by viniciusgugelmin** [comment]
```
        mounted() {
            Event.$on('move-to', this.moveTo , this.slide);
            Event.$on('set-disabled', this.setDisabled, this.disabled);
            this.moveTo();
        },

        methods: {
            moveTo(slide) {
                this.$refs.fpcontainer.$fullpage.moveTo(slide,  Number.isInteger(slide) ? true : false);
            },

            setDisabled(value) {
                this.$refs.fpcontainer.$fullpage.setDisabled(value);
            }
        },
```

**Comment by viniciusgugelmin** [comment]
```
{
                path: '',
                redirect: {name: 'sobre'}
            },
            {
                path: 'sobre',
                name: 'sobre',
                meta: {slide: 0},
                component: () => import('./views/Conteudo'),
            },
            {
                path: 'projetos',
                name: 'projetos',
                meta: {slide: 1},
                component: () => import('./views/Conteudo'),
            },
            {
                path: 'equipe',
                name: 'equipe',
                meta: {slide: 2},
                component: () => import('./views/Conteudo'),
            },
            {
                path: 'contato',
                name: 'contato',
                meta: {slide: 3},
                component: () => import('./views/Conteudo'),
            },
            {
                path: 'localizacao',
                name: 'localizacao',
                meta: {slide: 4},
                component: () => import('./views/Conteudo'),
            }
```

There's also a routes.js with this code. Basically if I change the meta "{slide: 4}" for other number (0, 1, 2, 3) it's all okay.

**Comment by abel-oye** [comment]
Does that mean there's no problem？

**Comment by viniciusgugelmin** [comment]
No, I can't start the page in the last slide.

**Comment by abel-oye** [comment]
I didn't notice. I thought there were only 4.

From the code snippet, no problem.

 if slide is 4, which slide to show?

**Comment by viniciusgugelmin** [comment]
You can see the problem in this site http://www.posted.com.br/
The slides run in this sequence: "sobre", "projetos", "equipe", "contato", "localizacao".
The last is slide, as I commented, is "localizacao" (http://www.posted.com.br/localizacao)

**Comment by abel-oye** [comment]
I found the problem. 
`js
moveTo(slide) {
                this.$refs.fpcontainer.$fullpage.moveTo(slide,  Number.isInteger(slide) ? true : false);
            },
`
When slide equals undefined, do not call moveTo.


`js
moveTo(slide) {
                if( Number.isInteger(slide)){
        this.$refs.fpcontainer.$fullpage.moveTo(slide,  Number.isInteger(slide));
}
            },
`
