### ISSUE TITLE
 wechat scroll  problem

### ISSUE THREAD

**Issue by chas125** [river-lee/vue-fullpage#8]
set overflow 'scroll' will make the page unscrollable in WeChat
tested in MIUI 9(android 7.1) and wechat devtool(0.7.0) on PC

**Comment by abel-oye** [comment]
Test results：wechat devtool v0.7.0 scrollTop 1px less than actual. MIUI 9 maybe the same. Could you please check it for me?

**Comment by chas125** [comment]
yes,i'm the same

**Comment by chas125** [comment]
i add 5px for the safe...

**Comment by abel-oye** [comment]
I'm going to check the reason.-_-!

**Comment by chas125** [comment]
and in the scrollable page there is an old question about '下拉露底' in Wechat ....
