### ISSUE TITLE
Component crash when Vue.js devtools is open

### ISSUE THREAD

**Issue by buroli** [river-lee/vue-fullpage#9]
Hi,

Strange bug but when you are in dev mode with webpack and vue-cli and open Vue dev tools component crash.

To reproduce :
- Open local url
- Open Chrome Dev tools
- Open Vue dev tools and switch to 'Events' tabs.

The component doesn't work anymore.
I don't know if it's related with the events emitted by the component ?

**Comment by buroli** [comment]
FYI, it also occurs on builded files.
Like your website example : https://river-lee.github.io/vue-fullpage/examples/

**Comment by abel-oye** [comment]
Thx, this bug is because page has not changed, but the way of triggering the “moveTo”, webkitTransitionEnd will not be invoked, unable to reset the state, resulting in failure to slide.
